TransportParams support in ClientOptions
ably/ably-flutter pull request #364
Opened 2022-04-07 12:00 UTC by ikurek

This should close https://github.com/ably/ably-flutter/issues/108. I've found out that this feature was implemented on Dart side, but it wasn't implemented in iOS and Android bridges, probably because of differences in implementation of these methods for each platform (iOS requires `NSDictionary` and Android requires `Param[]` array).  I've implemented bridges on each platform and now it seems to work fine 🙂

2022-04-07 12:35 UTC, KacperKluka requested changes

2022-04-07 13:41 UTC, ikurek commented on android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java
> +    Param[] o = null;
We definitely should, but if you look at the file, these variables are called `o` in every codec method 😞  I've decided to stick to the convention used previously, should I change it in that case? 🤔

2022-04-07 14:00 UTC, KacperKluka commented on android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java
> +    Param[] o = null;
I'd say let's make it the first one which has some meaningful names :grin: There's no need to align with a bad practice IMO :wink:

2022-04-07 16:01 UTC, ikurek commented on android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java
> +    Param[] o = null;
Fixed in https://github.com/ably/ably-flutter/pull/364/commits/2e40e666f277a9dc24bc51ef0cf24a72cb3fa851

2022-04-07 18:43 UTC, KacperKluka approved these changes
LGTM :+1:

2022-04-12 08:20 UTC, lukasz-szyszkowski approved these changes

2022-04-12 11:24 UTC, merged