Fixed iOS push module compilation issue on some versions of XCode
ably/ably-flutter pull request #373
Opened 2022-04-19 14:22 UTC by ikurek

This should solve https://github.com/ably/ably-flutter/issues/347. Apparently, for some combinations of Swift/XCode versions the compiler doesn't correctly recognize the `let guard` statements, which leads to `handle` and `channelName` being identified as nullable types, although they are guarded by specific checks before they are used. I've made a non-nullable, unwrapped versions of those variables to avoid those compilation errors.

2022-04-20 18:25 UTC, lawrence-forooghian commented
I think it might be worth us trying to reproduce this, so we can have more confidence in our fix. The `guard let foo = foo` syntax isn't new in Swift - it's been around for quite a while. Furthermore, somebody else has [reported it happening in Xcode 13.2](https://github.com/ably/ably-flutter/issues/347#issuecomment-1101310802), which is very new.

Can we try to get further information from the issue creators? Perhaps they could supply us with some sample code to reproduce the issue.

2022-04-21 08:35 UTC, ikurek commented
> I think it might be worth us trying to reproduce #347, so we can have more confidence in our fix. The `guard let foo = foo` syntax isn't new in Swift - it's been around for quite a while. Furthermore, somebody else has [reported it happening in Xcode 13.2](https://github.com/ably/ably-flutter/issues/347#issuecomment-1101310802), which is very new.
> 
> Can we try to get further information from the issue creators? Perhaps they could supply us with some sample code to reproduce the issue.

I'm aware that the `guard let` used here is a pretty standard structure for Swift code, but judging from the stacktrace that users provided, It's highly probable that it causes the compilation issue. 

I'm not very familiar with iOS development environment, but the issue seems to be device-specific and I failed to reproduce it on my machines, with XCode 12 and 13 😞   Since this is a compile-time problem, I don't think users will be able to support us with sample code - the problem lies within the Ably library, and users don't modify it on their side.

2022-04-21 14:53 UTC, QuintinWillison requested changes
I have sympathy for @lawrence-forooghian's suggestion, however I'm also keen for us to get this fix in front of the user that reported it, as well as other users potentially.

Do we have any idea if there may be other areas of this codebase at risk of this particular Swift compiler issue?

Also, I think it would be really helpful for you to add some commentary to the code where you use the either `nullable` prefix (as I suggest) or your `Unwrapped` suffix to explain exactly why this 'dance' is being done.

2022-04-21 14:56 UTC, QuintinWillison commented on ios/Classes/handlers/PushHandlers.swift
> +        var channelName: String?
Actually, on reflection (no pun intended 😜) maybe that variable prefix should be `optional` rather than `nullable`.

2022-04-21 16:29 UTC, ikurek commented on ios/Classes/handlers/PushHandlers.swift
> +        var channelName: String?
I'm not sure what's the convention in Swift for cases like that, but it makes sense to use `optional` for nilable values, so I changed this in https://github.com/ably/ably-flutter/pull/373/commits/5b3ce39dde0ca624e3dbb615486e9aca22ac99ef

2022-04-21 16:34 UTC, ikurek commented
The introduced fixes seem to solve the problem, confirmed by one of affected users here: https://github.com/ably/ably-flutter/issues/347#issuecomment-1105442118

2022-04-21 16:43 UTC, ikurek commented
> I have sympathy for @lawrence-forooghian's suggestion, however I'm also keen for us to get this fix in front of the user that reported it, as well as other users potentially.

This seems to be an edge case for specific versions of development tools. I managed to get the issue only in a few specific configurations of XCode / MacOS / Flutter versions and it seems to be some sort of compiler issue. I think the fix should be enough to solve the case.

> Do we have any idea if there may be other areas of this codebase at risk of this particular Swift compiler issue?

There isn't too much Swift code in the repository, it's mostly Objective C. I've checked and the problematic `guard let foo = foo` structure isn't used anywhere else in the codebase, so there should be no further issues with this

> Also, I think it would be really helpful for you to add some commentary to the code where you use the either `nullable` prefix (as I suggest) or your `Unwrapped` suffix to explain exactly why this 'dance' is being done.

I've left a comment with a short explanation and link to the issue in https://github.com/ably/ably-flutter/pull/373/commits/cf7b9cbae756f88c3f6d58ee40e0fe5ec2d16bc5

2022-04-22 08:10 UTC, QuintinWillison approved these changes

2022-04-25 17:27 UTC, lawrence-forooghian approved these changes
Happy to approve if @QuintinWillison is keen to get this merged as-is 👍

2022-04-26 09:00 UTC, merged