Fix for running didFinishLaunchingWithOptions
ably/ably-flutter pull request #433
Opened 2022-07-05 22:44 UTC by Neelansh-ns

Added fix for running `didFinishLaunchingWithOptions` in other registered plugins like uni_links.

Problem:

Since `didFinishLaunchingWithOptions` was returning NO, other plugins such as `uni_links`, also get the `initialAppLink` from `didFinishLaunchingWithOptions` were not able to run the function. This resulted in initialAppLink being `null` always.

2022-07-06 06:59 UTC, QuintinWillison commented
Thanks, @Neelansh-ns, for the contribution. ❤️ 
We'll take a proper look at this in due course, but my immediate observations...

From Apple's [documentation for `application:didFinishLaunchingWithOptions:`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application?language=objc) return value:

> NO if the app cannot handle the URL resource or continue a user activity, otherwise return YES. The return value is ignored if the app is launched as a result of a remote notification.

From Apple's [documentation for `application:didReceiveRemoteNotification:fetchCompletionHandler:`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application?language=objc), it looks like any return value is ignored as the return type is defined as `void`. Did you find that changing this return value had any impact on the problem you were solving with this fix, or is there a chance that just the `application:didFinishLaunchWithOptions:` change was the only remedy required?

We'll need to ascertain whether there was a good reason why an explicit choice to return `NO` was made. I expect that your fix is probably correct and that the current behaviour was likely lazy implementation on our behalf, for something that didn't have any visibility during testing due to the way that we have been testing. 🤔

2022-07-07 08:14 UTC, Neelansh-ns commented
> Did you find that changing this return value had any impact on the problem you were solving with this fix, or is there a chance that just the application:didFinishLaunchWithOptions: change was the only remedy required?

Yes @QuintinWillison , on changing the return type to YES, `didFinishLaunchingWithOptions` function runs for other plugins. You can try `uni_links` package. That's a great example to test this out. I have the same in my app.  I also confirmed by removing `ably_flutter` as a dependency.

2022-07-13 09:50 UTC, arturjaworski approved these changes

2022-07-13 09:53 UTC, JakubJankowski approved these changes

2022-07-13 10:01 UTC, JakubJankowski commented
Actually, let me take another look at why we're returning a bool in the `didReceiveRemoteNotification`, even though docs say it should be void.

2022-07-13 10:34 UTC, arturjaworski requested changes
Documentation for `application:didReceiveRemoteNotification:fetchCompletionHandler:` says that it should return `void` type. It looks like some old issue from our side. Please make a change to introduce `void` type.

`application:didFinishLaunchingWithOptions:` change looks good :+1:

2022-07-13 16:55 UTC, Neelansh-ns commented
Hi @arturjaworski 

The apple documentation says that it should have a return void type, but the header file `FlutterPlugin.h`, has a return type `BOOL`.
Refer: https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h#L97

So when we override the function with the `completionhandler`, we have to make the return type as `BOOL` itself instead of `void`.

The documentation asks us to return `YES` if the plugin handles the request.

<img width="772" alt="Screenshot 2022-07-13 at 10 25 00 PM" src="https://user-images.githubusercontent.com/22894247/178788956-d6b64059-1158-4ffd-95ec-5e3ea624678d.png">

```
- (BOOL)application:(UIApplication*)application
    didReceiveRemoteNotification:(NSDictionary*)userInfo
          fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler
```

2022-07-14 07:40 UTC, JakubJankowski commented
Yeah, good point. LGTM 👍

2022-07-14 13:23 UTC, arturjaworski approved these changes
@Neelansh-ns You are right. Looks good to me 👍

2022-07-18 15:20 UTC, QuintinWillison commented
I'm landing this PR despite the docs workflow failing, due to the fact that we've identified that it's failing because it's unable to access the org-level secret `ABLY_AWS_ACCOUNT_ID_SDK` - which is as expected. GitHub state:

> Secrets are not passed to workflows that are triggered by a pull request from a fork.

2022-07-18 15:20 UTC, merged