REST - Channels & publishing messages
ably/ably-flutter pull request #45
Opened 2020-09-14 20:14 UTC by tiholic

Satisfies

### Channels spec : IDL | [Ruby Spec](https://github.com/ably/ably-ruby-rest/blob/main/SPEC.md#ablyrestchannels)

TODO add checklist

### `#publish` method of Channel spec : IDL | [Ruby Spec](https://github.com/ably/ably-ruby-rest/blob/main/SPEC.md#ablyrestchannel)

TODO add checklist

### Message object spec : IDL | [Ruby Spec](https://github.com/ably/ably-ruby-rest/blob/main/SPEC.md#ablymodelsmessage)

TODO add checklist

### Channel object spec: [Ruby Spec](https://github.com/ably/ably-ruby-rest/blob/main/SPEC.md#ablyrestchannel-1)

`channel name` argument in `constructor`
- [ ] can be `UTF-8` string
- [ ] can be frozen `UTF-8` string
- [ ] if given as `SHIFT_JIS` string will be converted to `UTF-8`, but is compatible with original encoding
- [ ] if given as `ASCII_8BIT` string will be converted to `UTF-8`, but is compatible with original encoding
- [ ] **cannot** be `null`, or any other type

`name` argument of `#publish`

- [ ] `UTF_8` string is permitted
- [ ] `frozen UTF_8` string is permitted
- [ ] `SHIFT_JIS` string is permitted
- [ ] `ASCII_8BIT` string is permitted
- [ ] `int` is not permitted

### Channels object spec:  [IDL](https://docs.ably.io/client-lib-development-guide/features/#RSN1) | [Ruby Spec](https://github.com/ably/ably-ruby-rest/blob/main/SPEC.md#ablyrestchannels-1)

- [ ] (RSN1) Channels is a collection of Channel objects accessible through `Rest#channels`
- [ ] (RSN2) Methods should exist to check if a channel exists or iterate through the existing channels
- (RSN3) `Channels#get` function:
    - [ ] (RSN3a) Creates a new `Channel` object for the specified channel if none exists, or returns the existing channel. `ChannelOptions` can be provided in an optional second argument
    - [ ] (RSN3b) If options are provided, the options are set on the Channel
    - [ ] (RSN3c) Accessing an existing `Channel` with options in the form `Channels#get(channel, options)` will update the `options` on the channel and then return the existing `Channel` object. (Note that this is soft-deprecated and may be removed in a future release, so should not be implemented in new client libraries. The supported way to update a set of `ChannelOptions` is `Channel#setOptions`)
- (RSN4) `Channels#release` function:
    - [ ] (RSN4a) Takes one argument, the channel name, and releases the corresponding channel entity (that is, deletes it to allow it to be garbage collected)
    - [ ] (RSN4b) Calling `release()` with a channel name that does not correspond to an extant channel entity must return without error
    - [ ] (RSN4c) Calling `release()` with a channel name that corresponds to a channel that is in any state other than `INITIALIZED`, `DETACHED`, or `FAILED` must, instead of releasing the channel, raise an error with code `90001`

2020-10-05 10:11 UTC, zoechi requested changes

2021-03-12 21:19 UTC, tiholic commented on lib/src/impl/platform_object.dart
> +  Future<int> _acquireHandle() =>
Resolved in previous PRs

2021-03-12 21:19 UTC, tiholic commented on lib/src/impl/realtime/channels.dart
>    spec.AblyBase ably;
Resolved in earlier PRs

2021-03-12 21:30 UTC, tiholic commented on lib/src/impl/realtime/connection.dart
>    Realtime realtimePlatformObject;
addressed in 28167ab2961aa8cf82b6e20cfc14859b65078257

2021-05-07 05:52 UTC, jamienewcomb commented on lib/src/impl/realtime/connection.dart
>    Realtime realtimePlatformObject;
is this resolved now @tiholic ?

2021-05-20 09:21 UTC, tiholic commented on android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java
> +            new CodecPair<>(self::encodeAblyFlutterMessage, self::decodeAblyFlutterMessage));
I've updated indentation levels for continuation indent in Studio.

2021-05-20 09:26 UTC, tiholic commented on lib/src/codec.dart
> +  /// Encodes [TokenRequest] to a Map
suggestion accepted: a1fd1ea18fe7f5f80ba51da6a67d776fe2447a63

2021-05-20 09:27 UTC, tiholic commented on lib/src/codec.dart
> +  /// Encodes [TokenRequest] to a Map
Suggestion accepted: 8351bb8a73923027a0e794236a920f6dcf6a9289

2021-05-20 09:33 UTC, tiholic commented on lib/src/codec.dart
> +  Map<String, dynamic> _encodeErrorInfo(final ErrorInfo v) {
added commentary on all methods: bd6298413ec66a454c8f8dc19e5c41c7bd0c851c

_Ignored it on purpose earlier as private methods won't be included in docs._

2021-05-20 09:34 UTC, tiholic commented on lib/src/spec/common.dart
> +class _ChannelIterator<T> implements Iterator<T> {
Yes, first time I wrote a custom iterator. Expected it to be simpler!

2021-05-20 09:34 UTC, tiholic commented on lib/src/spec/common.dart
> +class _ChannelIterator<T> implements Iterator<T> {
Yes, first time I wrote a custom iterator in dart. Expected it to be simpler!

2021-05-20 10:58 UTC, tiholic commented on ios/Classes/AblyFlutterPlugin.m
> +    const id cbk = ^(ARTPaginatedResult<ARTMessage *> * _Nullable paginatedResult, ARTErrorInfo * _Nullable error) {
renamed: d552f096117318de9e721db3d739769baf841f4a

2021-05-20 10:59 UTC, tiholic commented on ios/Classes/codec/AblyPlatformConstants.m
> +@implementation TxRestChannelOptions
addressed: 7179b2dd6a9f8e4688d671d7f47b2a43284c21b8

2021-05-20 10:59 UTC, tiholic commented on ios/Classes/codec/AblyPlatformConstants.h
> +@interface TxRestChannelOptions : NSObject
addressed: 7179b2dd6a9f8e4688d671d7f47b2a43284c21b8

2021-05-20 10:59 UTC, tiholic commented on lib/src/spec/common.dart
> +  /// This is a private method to be overridden by implementation classes
addressed: 3166620f89e56a28538514b2b02da9e589305283

2021-05-22 16:47 UTC, tiholic commented on lib/src/impl/realtime/connection.dart
>    Realtime realtimePlatformObject;
@jamienewcomb yes

2021-05-22 17:09 UTC, tiholic commented on lib/src/spec/message.dart
> +        'Message extras must be either `Map`, `List` or `null`.'
fixed: 246e6b6ceb9a951348e9d169348905faf08fe4f4

2021-05-24 19:33 UTC, tiholic commented on lib/src/spec/message.dart
> +        'Message extras must be either `Map`, `List` or `null`.'
Further optimization of `MessageExtras` is being handled here: https://github.com/ably/ably-flutter/pull/123

2021-05-27 13:16 UTC, QuintinWillison approved these changes
I've not gone through line by line, though I have checked the commits you've submitted since my last review in order to resolve those conversations.

The `main` branch was out of date so I've boshed GitHub's update button, resolving that with the merge commit that is https://github.com/ably/ably-flutter/pull/45/commits/fa34b4340124032984fc03e0343ce5be4828b496.

Once checks pass then I'm happy to land this.

2021-05-27 14:24 UTC, merged