Release 1.2.27
ably/ably-flutter pull request #512
Opened 2024-03-05 14:40 UTC by sacOO7

2024-03-05 16:14 UTC, ttypic requested changes

2024-03-06 10:20 UTC, sacOO7 commented on example/ios/Podfile.lock
> +    - Ably (= 1.2.27)
updated !

2024-03-06 10:20 UTC, sacOO7 commented on example/ios/Podfile.lock
> +  - Ably (1.2.27):
updated !

2024-03-06 12:16 UTC, ttypic reviewed
LGTM!

2024-03-06 12:16 UTC, ttypic approved these changes

2024-03-06 12:36 UTC, merged